site_name: Human Phenotype Ontology Internationalisation Effort
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js

nav:
  - About HPO translations: index.md
  - How to submit a language profile: submit.md
  - How to maintain a language profile: maintain.md
  - Contact: contact.md
  - Translations: translations.md
  - Language translations:
    - Arabic: translations/ar.md
    - Chinese: translations/zh.md
    - Czech: translations/cs.md
    - Dusun: translations/dtp.md
    - Dutch: translations/nl.md
    - Finnish: translations/fi.md
    - French: translations/fr.md
    - German: translations/de.md
    - Italian: translations/it.md
    - Japanese: translations/ja.md
    - Nyangumarta: translations/nna.md
    - Portuguese: translations/pt.md
    - Spanish: translations/es.md
    - Thai: translations/th.md
    - Turkish: translations/tr.md
    - Twi: translations/tw.md
repo_url: https://github.com/obophenotype/hpo-translations/
site_url: https://obophenotype.github.io/hpo-translations/
edit_uri: docs/
